version: '3.3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: super_secret_password
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      MYSQL_DATABASE: ecoplant
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init-scripts:/docker-entrypoint-initdb.d
      - ./mysql/init-scripts/energy_data.csv:/var/lib/mysql-files/energy_data.csv
    restart: always
    networks:
      - backend
    
  node:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: node_container
    volumes:
      - ./server:/app
      - ./server/node_modules
    ports:
      - 3001:3001
    depends_on:
      - mysql
    networks:
      - backend

  nginx:
    container_name: nginx_container
    build: 
      context: ./client
      dockerfile: Dockerfile.prod
    volumes:
      - ./client/build
    ports:
      - 3000:80
    depends_on:
      - node
    networks:
      - backend

networks:
  backend:
    driver: bridge
